### ISSUE TITLE
where to find the `BD.nwk.json` file?

### ISSUE THREAD

**Issue by liamxg** [LeoFeatherstone/phylodynamicsFundamentals#1]
Dear @LeoFeatherstone ,

Could you please tell me where to find the `BD.nwk.json` file? 
Thanks.

Best,
Liam

**Comment by LeoFeatherstone** [comment]
Hi Liam,

You will need to produce it by running the `BD_sim_template.xml` file. However, nowadays I would use ReMaster instead of Master to do this with BEAST v2.

All the best,
Leo

**Comment by liamxg** [comment]
Dear @LeoFeatherstone ,

Thanks, 

It this the results for `epiFig`:

<img width="705" alt="image" src="https://github.com/user-attachments/assets/7b68ca9c-93f8-48c6-b178-12d05f4282a6">

Best,
Liam
